In [94]:
import pandas as pd 
import numpy as np
from sklearn import linear_model

In [5]:
t = pd.read_excel("/Users/igabo/Desktop/Tarea 1 semi/Tarea 1/lineal_horm.xlsx")

In [6]:
list(t.loc[t['lote'] == 'A']['horas'])

[99, 152, 293, 155, 196, 53, 184, 171, 52]

In [7]:
k_A = t.loc[t['lote'] == 'A'].sample(n=10, replace = True)
k_A

lote  horas  monto
8    A     52   30.4
0    A     99   25.8
1    A    152   20.5
7    A    171   20.9
6    A    184   20.9
5    A     53   31.1
2    A    293   14.3
7    A    171   20.9
6    A    184   20.9
3    A    155   23.2

In [8]:
k_A['horas'].to_numpy()

array([ 52,  99, 152, 171, 184,  53, 293, 171, 184, 155])

In [9]:
k_B = t.loc[t['lote'] == 'B'].sample(n=10, replace = True)
k_B

lote  horas  monto
15    B    151   24.1
14    B    296   18.0
12    B     29   32.5
13    B     76   32.0
10    B    385   11.6
14    B    296   18.0
10    B    385   11.6
14    B    296   18.0
17    B    209   25.8
13    B     76   32.0

In [10]:
k_C = t.loc[t['lote'] == 'C'].sample(n=10, replace = True)
k_C

lote  horas  monto
24    C    150   25.4
26    C    125   28.5
25    C    107   31.7
23    C     49   32.5
26    C    125   28.5
19    C    188   22.0
25    C    107   31.7
24    C    150   25.4
18    C    119   28.8
19    C    188   22.0

In [11]:
# 30 elementos aleatorios de los lotes
T = k_A.append(k_B).append(k_C)
T

lote  horas  monto
8     A     52   30.4
0     A     99   25.8
1     A    152   20.5
7     A    171   20.9
6     A    184   20.9
5     A     53   31.1
2     A    293   14.3
7     A    171   20.9
6     A    184   20.9
3     A    155   23.2
15    B    151   24.1
14    B    296   18.0
12    B     29   32.5
13    B     76   32.0
10    B    385   11.6
14    B    296   18.0
10    B    385   11.6
14    B    296   18.0
17    B    209   25.8
13    B     76   32.0
24    C    150   25.4
26    C    125   28.5
25    C    107   31.7
23    C     49   32.5
26    C    125   28.5
19    C    188   22.0
25    C    107   31.7
24    C    150   25.4
18    C    119   28.8
19    C    188   22.0

In [92]:
reg = linear_model.LinearRegression()

In [104]:
x = T[["horas"]]

In [86]:
# y = T['monto'].to_numpy() 
# print(y)
y = T[["monto"]]

In [36]:
# x = np.array(x).reshape((-1, 1))
# x

In [98]:
reg.fit(x, y)

LinearRegression()

In [106]:
b_0 = reg.intercept_ # Beta_0
print(b_0)

[34.59382538]


In [110]:
b_1 = reg.coef_[0] # Beta_1
print(b_1)

[-0.06150463]


In [114]:
print(y)

    monto
8    30.4
0    25.8
1    20.5
7    20.9
6    20.9
5    31.1
2    14.3
7    20.9
6    20.9
3    23.2
15   24.1
14   18.0
12   32.5
13   32.0
10   11.6
14   18.0
10   11.6
14   18.0
17   25.8
13   32.0
24   25.4
26   28.5
25   31.7
23   32.5
26   28.5
19   22.0
25   31.7
24   25.4
18   28.8
19   22.0


In [118]:
y_pred = reg.predict(x)

In [121]:
y_pred

array([[31.39558447],
       [28.50486673],
       [25.24512119],
       [24.07653317],
       [23.27697294],
       [31.33407984],
       [16.57296796],
       [24.07653317],
       [23.27697294],
       [25.06060729],
       [25.30662582],
       [16.38845407],
       [32.81019103],
       [29.91947328],
       [10.91454175],
       [16.38845407],
       [10.91454175],
       [16.38845407],
       [21.73935712],
       [29.91947328],
       [25.36813046],
       [26.90574628],
       [28.01282967],
       [31.58009837],
       [26.90574628],
       [23.03095441],
       [28.01282967],
       [25.36813046],
       [27.27477407],
       [23.03095441]])

In [124]:
y_estim = y_pred.reshape(-1)
y_estim

array([31.39558447, 28.50486673, 25.24512119, 24.07653317, 23.27697294,
       31.33407984, 16.57296796, 24.07653317, 23.27697294, 25.06060729,
       25.30662582, 16.38845407, 32.81019103, 29.91947328, 10.91454175,
       16.38845407, 10.91454175, 16.38845407, 21.73935712, 29.91947328,
       25.36813046, 26.90574628, 28.01282967, 31.58009837, 26.90574628,
       23.03095441, 28.01282967, 25.36813046, 27.27477407, 23.03095441])

In [125]:
x = x.to_numpy().reshape(-1)
x

array([ 52,  99, 152, 171, 184,  53, 293, 171, 184, 155, 151, 296,  29,
        76, 385, 296, 385, 296, 209,  76, 150, 125, 107,  49, 125, 188,
       107, 150, 119, 188])

In [127]:
y_real = y.to_numpy().reshape(-1)
y_real

In [134]:
residual = y_real - y_estim
residual

array([-0.99558447, -2.70486673, -4.74512119, -3.17653317, -2.37697294,
       -0.23407984, -2.27296796, -3.17653317, -2.37697294, -1.86060729,
       -1.20662582,  1.61154593, -0.31019103,  2.08052672,  0.68545825,
        1.61154593,  0.68545825,  1.61154593,  4.06064288,  2.08052672,
        0.03186954,  1.59425372,  3.68717033,  0.91990163,  1.59425372,
       -1.03095441,  3.68717033,  0.03186954,  1.52522593, -1.03095441])

In [144]:
den = sum((x - np.mean(x))**2)
num = sum(residual**2)/(30-2)
err = np.sqrt(num / den)
err

0.0044584334629002645